import { Link } from "react-router-dom";
import { ArrowLeft, ArrowUpRight, CheckCircle2, Download, MoreHorizontal, SlidersHorizontal, Sparkles, Trophy } from "lucide-react";

const rankedCandidates = [
  { rank: 1, name: "Maya Chen", initials: "MC", role: "Senior Product Designer", score: 96, color: "bg-[#dce8f5] text-[#174575]", skills: ["Figma", "Design systems", "Research"], reason: "Strong product thinking and deep design-system experience." },
  { rank: 2, name: "Jordan Rivera", initials: "JR", role: "Product Designer", score: 91, color: "bg-[#fbe6d2] text-[#9a4d16]", skills: ["Figma", "Prototyping", "UX strategy"], reason: "Excellent interaction design with relevant B2B experience." },
  { rank: 3, name: "Olivia Wilson", initials: "OW", role: "UX Researcher", score: 87, color: "bg-[#e4e8f2] text-[#3d4e76]", skills: ["User research", "Analytics", "Service design"], reason: "Brings rigorous research practice and clear customer insight." },
  { rank: 4, name: "Noah Patel", initials: "NP", role: "Product Designer", score: 82, color: "bg-[#dcefe9] text-[#17624e]", skills: ["Figma", "Interaction design", "HTML"], reason: "Solid foundation with a strong eye for accessible interfaces." },
];

export default function CandidateRankingPage() {
  return (
    <div className="space-y-5">
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Link to="/candidates" className="mb-3 inline-flex items-center gap-1.5 text-xs font-semibold text-[#58708d] hover:text-[#0b3767]"><ArrowLeft size={14} /> All candidates</Link><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-[#e07b25]">AI shortlist</p><h1 className="mt-1 text-2xl font-bold text-[#15395f]">Candidate ranking</h1><p className="mt-1 text-sm text-[#71829a]">Product Designer · scored against 12 role requirements</p></div><div className="flex gap-2"><button type="button" className="inline-flex items-center gap-2 rounded-md border border-[#dfe6ef] bg-white px-3 py-2.5 text-xs font-semibold text-[#365372] hover:bg-[#f5f8fb]"><Download size={14} /> Export</button><button type="button" className="inline-flex items-center gap-2 rounded-md bg-[#0b3767] px-3 py-2.5 text-xs font-semibold text-white hover:bg-[#174b80]"><CheckCircle2 size={14} /> Shortlist top 3</button></div></div>
      <section className="grid gap-4 lg:grid-cols-[1fr_280px]"><div className="rounded-lg border border-[#dfe6ef] bg-white p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-[#8191a6]">Ranking confidence</p><div className="mt-2 flex items-center gap-3"><span className="text-3xl font-bold text-[#15395f]">94%</span><span className="inline-flex items-center gap-1 text-xs font-semibold text-[#16805d]"><Sparkles size={14} /> High confidence</span></div></div><div className="flex h-12 w-12 items-center justify-center rounded-full border-[5px] border-[#dcefe9] text-[#16805d]"><Trophy size={19} /></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-[#edf1f5]"><div className="h-full w-[94%] rounded-full bg-[#16805d]" /></div><div className="mt-3 flex justify-between text-[11px] text-[#8191a6]"><span>12 criteria analyzed</span><span>128 profiles evaluated</span></div></div><div className="rounded-lg border border-[#dfe6ef] bg-[#0b3767] p-5 text-white"><div className="flex items-center gap-2 text-[#bcd0e8]"><SlidersHorizontal size={15} /><span className="text-xs font-semibold">Ranking settings</span></div><p className="mt-3 text-sm font-semibold">Role requirements</p><p className="mt-1 text-[11px] leading-5 text-[#b5cae1]">Skills 45% · Experience 30% · Education 15% · Location 10%</p><button type="button" className="mt-4 text-[11px] font-semibold text-white underline underline-offset-4">Adjust weighting</button></div></section>
      <section className="rounded-lg border border-[#dfe6ef] bg-white"><div className="flex items-center justify-between border-b border-[#e8edf3] px-5 py-4"><div><h2 className="text-sm font-bold text-[#17395f]">Recommended candidates</h2><p className="mt-1 text-xs text-[#8191a6]">Ordered by match to the selected role</p></div><button type="button" aria-label="More ranking options" className="rounded p-2 text-[#8191a6] hover:bg-[#f4f7fa]"><MoreHorizontal size={18} /></button></div><div className="divide-y divide-[#edf1f5]">{rankedCandidates.map((candidate) => <div key={candidate.name} className="flex flex-col gap-4 p-5 lg:flex-row lg:items-center"><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-md ${candidate.rank === 1 ? "bg-[#fff0d9] text-[#ad6418]" : "bg-[#f2f5f8] text-[#71829a]"}`}><span className="text-sm font-bold">{candidate.rank}</span></div><div className="flex min-w-0 flex-1 items-center gap-3"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-full text-xs font-bold ${candidate.color}`}>{candidate.initials}</span><div className="min-w-0"><Link to={`/candidates/${candidate.name.toLowerCase().replace(" ", "-")}`} className="block truncate text-sm font-semibold text-[#17395f] hover:text-[#315b91]">{candidate.name}</Link><p className="mt-0.5 text-[11px] text-[#8191a6]">{candidate.role}</p></div></div><div className="min-w-[180px] flex-1"><div className="mb-1 flex justify-between text-[10px] font-semibold text-[#8191a6]"><span>Match score</span><span className="text-[#16805d]">{candidate.score}%</span></div><div className="h-2 rounded-full bg-[#edf1f5]"><div className="h-full rounded-full bg-[#16805d]" style={{ width: `${candidate.score}%` }} /></div></div><div className="flex flex-1 flex-wrap gap-1.5">{candidate.skills.map((skill) => <span key={skill} className="rounded bg-[#eef3f8] px-2 py-1 text-[10px] font-medium text-[#49627f]">{skill}</span>)}</div><p className="hidden max-w-[230px] text-[11px] leading-4 text-[#71829a] xl:block">{candidate.reason}</p><Link to={`/candidates/${candidate.name.toLowerCase().replace(" ", "-")}`} aria-label={`View ${candidate.name}`} className="rounded p-2 text-[#71829a] hover:bg-[#eef3f8] hover:text-[#0b3767]"><ArrowUpRight size={17} /></Link></div>)}</div></section>
    </div>
  );
}
